# Generated by Django 5.2.6 on 2025-09-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leetcode',
            name='answer',
        ),
        migrations.AddField(
            model_name='leetcode',
            name='difficulty',
            field=models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='solution',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='thinking',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='leetcode',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
